Update README.md
snyk/kubernetes-scanner pull request #86
Opened 2024-08-30 16:49 UTC by schottsfired

The first part of the command in <> was confusing, I had to look it up to confirm it's a free-form input.

This change should make it clearer that it's a free-form secret name.

2024-08-30 16:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/snyk/kubernetes-scanner?pullRequest=86) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/snyk/kubernetes-scanner?pullRequest=86) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/snyk/kubernetes-scanner?pullRequest=86) it.</sub>

2024-09-02 11:04 UTC, jaspervdj-snyk requested changes
This seems good, but there's another reference to `<secret containing your auth credentials>` further down in the README, we would want to make sure these are consistently used

2024-09-03 13:59 UTC, schottsfired commented
Ah thanks @jaspervdj-snyk and good call. I didn't notice it was referenced twice.

I'll update the second reference as well, hang tight.

2024-09-03 14:08 UTC, schottsfired commented
Hi @jaspervdj-snyk , should be good to go now.

2024-09-03 14:41 UTC, jaspervdj-snyk approved these changes

2024-09-03 15:46 UTC, merged

2025-02-10 10:17 UTC, jaspervdj-snyk commented
:tada: This PR is included in version 0.22.6 :tada:

The release is available on [GitHub release](https://github.com/snyk/kubernetes-scanner/releases/tag/v0.22.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: